branch-defaults:
  default:
    environment: null
    group_suffix: null
  master:
    environment: null
    group_suffix: null
environment-defaults:
  WeatherMonitoring4:
    branch: null
    repository: null
global:
  application_name: WeatherMonitoring4
  branch: null
  default_ec2_keyname: aws-eb2
  default_platform: Puma with Ruby 2.6 running on 64bit Amazon Linux
  default_region: ca-central-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
